### ISSUE TITLE
total size of new array must be unchanged

### ISSUE THREAD

**Issue by Hx96** [AstarLight/Satellite-Segmentation#23]
将所有的input_shape改成 input_shape=(img_w,img_h,3)  keras有input_shape 通道参数在前，和通道参数在后之分

**Comment by menghuadeng** [comment]
你好，请问你模型预测结果出来了吗？我预测的结果是黑漆漆的一团。 @Hx96

**Comment by Hx96** [comment]
出来了，结果 你可以用matlab imagesc 来显示

**Comment by Yuyiba** [comment]
> 出来了，结果 你可以用matlab imagesc 来显示

你好，我也遇到了同样的问题，请问具体是怎么转换的？谢谢啦等待回复

**Comment by Hx96** [comment]
matlab imread()读入图像 imagesc()显示图像

**Comment by Yuyiba** [comment]
> matlab imread()读入图像 imagesc()显示图像

可以 加个联系方式吗？ imagesc函数里面的参数需要怎么设置，我现在读出来是一片青色……

**Comment by Yuyiba** [comment]
大哥 在线等候=，=

**Comment by Hx96** [comment]
qq 1014920159

**Comment by FaithLikeJob** [comment]
我结果也是黑的，怎样解决可以告知一下吗

**Comment by Ophelia20444** [comment]
> qq 1014920159

Traceback (most recent call last):
  File "segnet_train.py", line 258, in <module>
    train(args)  
  File "segnet_train.py", line 214, in train
    model = SegNet()  
  File "segnet_train.py", line 138, in SegNet
    model.add(MaxPooling2D(pool_size=(2, 2)))
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,1,128,128].
请问你知道这类问题该怎么解决吗？我并没有对代码进行修改，但是在pycharm上运行时会出现这样的错误。

**Comment by FaithLikeJob** [comment]
修改一下axis

**Comment by FaithLikeJob** [comment]
或者是keras的输入顺序有问题

**Comment by Ophelia20444** [comment]
> 或者是keras的输入顺序有问题

谢谢谢谢，找到了。还是tf后端差异的问题，也是输入shape需要改成w_img,h_img,3
