### ISSUE TITLE
请问如何进行预处理啊？作者的gen_dataset就是预处理么？

### ISSUE THREAD

**Issue by GusRoth** [AstarLight/Satellite-Segmentation#34]
还是有其他的方法先对原始数据进行处理？

**Comment by MichealRay** [comment]
我是直接用gen_dataset生成数据unet和segnet所需的数据的，其实就是做了简单的增强

**Comment by Ophelia20444** [comment]
> 我是直接用gen_dataset生成数据unet和segnet所需的数据的，其实就是做了简单的增强

求助！我想借用gen_dataset.py对我下载的ISPRS的训练影像和label进行分割，但是我把图像读取的路径改了之后运行结果报错了：
runfile('/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir='/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg')


  0%|          | 0/33 [00:00<?, ?it/s]creating dataset...


  3%|▎         | 1/33 [00:12<06:28, 12.13s/it]Traceback (most recent call last):

  File "<ipython-input-19-244e145230f1>", line 1, in <module>
    runfile('/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir='/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg')

  File "/opt/Anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/opt/Anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py", line 104, in <module>
    creat_dataset(mode='augment')

  File "/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py", line 86, in creat_dataset
    label_roi = label_img[random_height: random_height + img_h, random_width: random_width + img_w]

TypeError: 'NoneType' object is not subscriptable

求助这个问题该怎么解决啊？

**Comment by MichealRay** [comment]
hi，Ophelia20444 . 你试试runfile(r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir=r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg')

**Comment by Ophelia20444** [comment]
谢谢，我还在继续尝试！




------------------ 原始邮件 ------------------
发件人: "ZKL"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 上午8:32
收件人: "AstarLight/Satellite-Segmentation"<Satellite-Segmentation@noreply.github.com>; 
抄送: "蝴蝶骨"<shanshan_han@foxmail.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [AstarLight/Satellite-Segmentation] 请问如何进行预处理啊？作者的gen_dataset就是预处理么？ (#34)




hi，Ophelia20444 . 你试试runfile(r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir=r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg')

**Comment by xyh-qz** [comment]
> 谢谢，我还在继续尝试！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ZKL"<notifications@github.com>; 发送时间: 2019年4月22日(星期一) 上午8:32 收件人: "AstarLight/Satellite-Segmentation"<Satellite-Segmentation@noreply.github.com>; 抄送: "蝴蝶骨"<shanshan_han@foxmail.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [AstarLight/Satellite-Segmentation] 请问如何进行预处理啊？作者的gen_dataset就是预处理么？ (#34) hi，Ophelia20444 . 你试试runfile(r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir=r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg') — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你好，我也遇到了这个问题，请问你是怎么解决的

**Comment by Ophelia20444** [comment]
> > 谢谢，我还在继续尝试！
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "ZKL"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年4月22日(星期一) 上午8:32 收件人: "AstarLight/Satellite-Segmentation"[Satellite-Segmentation@noreply.github.com](mailto:Satellite-Segmentation@noreply.github.com); 抄送: "蝴蝶骨"[shanshan_han@foxmail.com](mailto:shanshan_han@foxmail.com); "Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [AstarLight/Satellite-Segmentation] 请问如何进行预处理啊？作者的gen_dataset就是预处理么？ (#34) hi，Ophelia20444 . 你试试runfile(r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg/gen_dataset.py', wdir=r'/media/usser/新加卷/HSS/Satellite-Segmentation-master/segnet/rawimg') — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 你好，我也遇到了这个问题，请问你是怎么解决的

嗯……我是把所有用cv2的命令都改为pillow调用……因为还没找到原因

**Comment by 8023AiCGZ** [comment]
gen_dataset切割后的label和src没有了坐标系，打开后label1和src1、label2和src2、label3和src3、、、、、、、都不是一一对应的，这个对结果没有影响吗
