### ISSUE TITLE
程序训练结束之后出现了‘function’ object has no attribute 'called',类似这样的错误警告，想问一下有人知道问题是出在哪吗？

### ISSUE THREAD

**Issue by Ophelia20444** [AstarLight/Satellite-Segmentation#38]
训练的时候并没有出什么问题，但是在训练过程结束之后出现了下面这些提示：
Epoch 30/30
703/703 [==============================] - 1410s 2s/step - loss: 0.2347 - acc: 0.9036 - val_loss: 1.0093 - val_acc: 0.7139
Traceback (most recent call last):

  File "<ipython-input-44-8eec5ae5e7bb>", line 1, in <module>
    get_ipython().run_line_magic('run', 'segnet_train.py -m segnet.h5')

  File "/opt/Anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2287, in run_line_magic
    result = fn(*args,**kwargs)

  File "<decorator-gen-60>", line 2, in run

  File "/opt/Anaconda3/lib/python3.7/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/opt/Anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 807, in run
    run()

  File "/opt/Anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 793, in run
    exit_ignore=exit_ignore)

  File "/opt/Anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 180, in mpl_execfile
    if plt.draw_if_interactive.called:

AttributeError: 'function' object has no attribute 'called'

我真的是看不出来是哪里的问题……有人知道吗？

**Comment by ZouLiSha** [comment]
同样的问题，你解决了吗

**Comment by ruose1314** [comment]
pip install ipython --upgrade --user
在terminal运行这个指令这行解决了我的问题
