### ISSUE TITLE
change the dataset and train

### ISSUE THREAD

**Issue by zhaojw219** [AstarLight/Satellite-Segmentation#45]
When I changed my own data set and executed the training code segnet_train.py, I encountered the following error:
Traceback (most recent call last):
  File "segnet_train.py", line 284, in <module>
    train(args)  
  File "segnet_train.py", line 247, in train
    validation_data=generateValidData(BS,val_set), steps_per_epoch=train_numb//BS, max_queue_size=1) 
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/home/gnss/anaconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/home/gnss/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "segnet_train.py", line 108, in generateData
    train_label = labelencoder.transform(train_label)  
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 257, in transform
    _, y = _encode(y, uniques=self.classes_, encode=True)
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 110, in _encode
    return _encode_numpy(values, uniques, encode)
  File "/home/gnss/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 53, in _encode_numpy
    % str(diff))
ValueError: y contains previously unseen labels: [7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 15.0]
This seems to be a problem with the label? Thank you for helping me.

**Comment by wcl6** [comment]
我也遇到了同样的问题，请问您解决了吗，是怎么解决的？
